//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTFRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public divisions()
        {
            this.Researcher_tbl = new HashSet<Researcher_tbl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int department_id { get; set; }
        public int Status { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual Status_tbl Status_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Researcher_tbl> Researcher_tbl { get; set; }
    }
}
