//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTFRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchProject_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResearchProject_tbl()
        {
            this.ResearchAssistant_tbl = new HashSet<ResearchAssistant_tbl>();
            this.ResearchFile_tbl = new HashSet<ResearchFile_tbl>();
        }
    
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> FiscalYear { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int TypeECID { get; set; }
        public string HeadResearcherId { get; set; }
        public string ECApprovalCode { get; set; }
        public Nullable<System.DateTime> ECApprovalDate { get; set; }
        public Nullable<System.DateTime> ECExpirationDate { get; set; }
        public Nullable<System.DateTime> ResearchApprovalDate { get; set; }
        public Nullable<System.DateTime> ResearchExpirationDate { get; set; }
        public string Note { get; set; }
        public int StatusProjectID { get; set; }
        public string sut_hospital_grant_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchAssistant_tbl> ResearchAssistant_tbl { get; set; }
        public virtual Researcher_tbl Researcher_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchFile_tbl> ResearchFile_tbl { get; set; }
        public virtual StatusProject_tbl StatusProject_tbl { get; set; }
        public virtual TypeEC_tbl TypeEC_tbl { get; set; }
    }
}
