//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTFRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchAssistant_tbl
    {
        public int ResearchAssistantID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ResearcherNumber { get; set; }
    
        public virtual ResearchProject_tbl ResearchProject_tbl { get; set; }
        public virtual Researcher_tbl Researcher_tbl { get; set; }
    }
}
