//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTFRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Researcher_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Researcher_tbl()
        {
            this.ResearchAssistant_tbl = new HashSet<ResearchAssistant_tbl>();
            this.ResearchProject_tbl = new HashSet<ResearchProject_tbl>();
        }
    
        public string ResearcherNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> work_group_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<int> TypeResearch { get; set; }
        public string title { get; set; }
        public string OtherInfo { get; set; }
    
        public virtual department department { get; set; }
        public virtual division division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchAssistant_tbl> ResearchAssistant_tbl { get; set; }
        public virtual TypeResearch TypeResearch1 { get; set; }
        public virtual work_groups work_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchProject_tbl> ResearchProject_tbl { get; set; }
    }
}
