//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTFRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ResearchProject
    {
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> FiscalYear { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public int TypeECID { get; set; }
        public string HeadResearcherId { get; set; }
        public string ECApprovalCode { get; set; }
        public Nullable<System.DateTime> ECApprovalDate { get; set; }
        public Nullable<System.DateTime> ECExpirationDate { get; set; }
        public Nullable<System.DateTime> ResearchApprovalDate { get; set; }
        public Nullable<System.DateTime> ResearchExpirationDate { get; set; }
        public string Note { get; set; }
        public int StatusProjectID { get; set; }
        public string sut_hospital_grant_code { get; set; }
        public string HeadResearcherFlag { get; set; }
        public string HeadResearcherName { get; set; }
        public Nullable<int> HeadResearcherNameDivID { get; set; }
        public string HeadResearcherNameDivName { get; set; }
        public string HeadResearcherGroupName { get; set; }
        public string HeadResearcherTypeResearch { get; set; }
        public string ResearchAssistantFlag { get; set; }
        public string ResearchAssistantName { get; set; }
        public string ResearchAssistantDvivsionName { get; set; }
        public string ResearchAssistantDepartment { get; set; }
        public string ResearchAssistantGroupName { get; set; }
        public string AssistantResearcherTypeResearch { get; set; }
    }
}
